-- =============================================
-- schema.sql - テーブル定義（H2 / PostgreSQL 互換）
-- =============================================
CREATE TABLE IF NOT EXISTS rehea_analysis_correction_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INT NOT NULL,
    wrong_text VARCHAR(255) NOT NULL,
    correct_text VARCHAR(255) NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (wrong_text)
);
CREATE TABLE IF NOT EXISTS rehea_analysis_instrument_keyword_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name VARCHAR(255) NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (canonical_name, keyword)
);
CREATE TABLE IF NOT EXISTS rehea_analysis_include_keyword_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (keyword)
);
CREATE TABLE IF NOT EXISTS rehea_analysis_exclude_pattern_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (pattern)
);
CREATE TABLE IF NOT EXISTS rehea_analysis_measure_pattern_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (pattern)
);
CREATE TABLE IF NOT EXISTS rehea_analysis_mark_pattern_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (pattern)
);
-- =============================================
-- orch_mst テーブル（オーケストラ団体マスタ）
-- =============================================
CREATE TABLE IF NOT EXISTS orch_mst (
    orch_id VARCHAR(6) NOT NULL,
    orch_name VARCHAR(64) NOT NULL,
    orch_name_en VARCHAR(64),
    orch_type VARCHAR(10),
    homepage_url VARCHAR(256),
    description TEXT,
    activity BOOLEAN,
    pro_state INT,
    is_public BOOLEAN,
    creator INT,
    since INT,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (orch_id),
    UNIQUE (orch_name)
);
-- =============================================
-- concert テーブル（演奏会データ）
-- =============================================
CREATE TABLE IF NOT EXISTS concert (
    concert_id VARCHAR(12) NOT NULL,
    orch_id VARCHAR(6) NOT NULL,
    concert_main_id VARCHAR(12) NOT NULL,
    concert_sub_id VARCHAR(2) NOT NULL,
    concert_name VARCHAR(128),
    music_descript TEXT,
    conductor_id BIGINT,
    conductor_name VARCHAR(20),
    concert_num BIGINT,
    hall_id VARCHAR(6),
    hall_branch_id BIGINT,
    place_name VARCHAR(64),
    concert_date VARCHAR(12),
    open_time VARCHAR(6),
    open_space VARCHAR(6),
    price BIGINT,
    price_under_cond VARCHAR(16),
    price_under BIGINT,
    teket_url VARCHAR(128),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (concert_id)
);
-- =============================================
-- person テーブル（人物データ）
-- =============================================
CREATE TABLE IF NOT EXISTS person (
    person_id BIGINT NOT NULL,
    last_name VARCHAR(8) NOT NULL,
    first_name VARCHAR(8) NOT NULL,
    old_name VARCHAR(8),
    last_name_kana VARCHAR(12),
    first_name_kana VARCHAR(12),
    last_name_kana_estimate VARCHAR(12) NOT NULL,
    first_name_kana_estimate VARCHAR(12) NOT NULL,
    musician_status VARCHAR(12),
    main_active_instrument VARCHAR(32),
    main_active_orch VARCHAR(32),
    orch_since INT,
    account VARCHAR(32),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (person_id)
);
-- =============================================
-- category テーブル（区分マスタ）
-- categ_type: 区分種別（例: MUSIC_STATE, MUSIC_TYPE）, categ_id: 区分ID
-- =============================================
CREATE TABLE IF NOT EXISTS category (
    categ_type VARCHAR(32) NOT NULL,
    categ_id VARCHAR(12) NOT NULL,
    categ_alter_id VARCHAR(32),
    name VARCHAR(256),
    name_jp VARCHAR(128),
    prop_str_1 TEXT,
    prop_str_2 VARCHAR(128),
    prop_num_1 INT,
    prop_num_2 INT,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (categ_type, categ_id)
);
-- =============================================
-- concert_lesson テーブル（練習データ）
-- =============================================
CREATE TABLE IF NOT EXISTS concert_lesson (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id VARCHAR(12) NOT NULL,
    branch_no INT NOT NULL,
    lesson_date DATE NOT NULL,
    lesson_start_time_str VARCHAR(32),
    lesson_end_time_str VARCHAR(32),
    lesson_start_time TIMESTAMP,
    lesson_end_time TIMESTAMP,
    place_name VARCHAR(64),
    contain VARCHAR(256),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    CONSTRAINT fk_concert_lesson_concert FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);
CREATE INDEX IF NOT EXISTS idx_concert_lesson_concert ON concert_lesson (concert_id);
-- =============================================
-- rehea_analysis_data テーブル（リハーサル音声解析結果）
--   analysis_id は YouTube/SRT の字幕データハッシュ、またはリアルタイム取得時刻。
-- =============================================
CREATE TABLE IF NOT EXISTS rehea_analysis_data (
    analysis_id VARCHAR(64) NOT NULL,
    lesson_id BIGINT,
    concert_id VARCHAR(12),
    branch_no INT,
    lesson_date DATE,
    download_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (analysis_id),
    CONSTRAINT fk_rehea_analysis_data_lesson FOREIGN KEY (lesson_id) REFERENCES concert_lesson (id),
    CONSTRAINT fk_rehea_analysis_data_concert FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);
-- =============================================
-- rehea_analysis_data_member テーブル（解析結果の指摘明細）
-- =============================================
CREATE TABLE IF NOT EXISTS rehea_analysis_data_member (
    analysis_id VARCHAR(64) NOT NULL,
    lesson_at BIGINT NOT NULL,
    measure VARCHAR(256),
    instrument VARCHAR(256),
    instruction TEXT,
    PRIMARY KEY (analysis_id, lesson_at),
    CONSTRAINT fk_rehea_analysis_data_member_analysis FOREIGN KEY (analysis_id) REFERENCES rehea_analysis_data (analysis_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_rehea_analysis_data_lesson ON rehea_analysis_data (lesson_id);
CREATE INDEX IF NOT EXISTS idx_rehea_analysis_data_member_analysis ON rehea_analysis_data_member (analysis_id);
-- =============================================
-- app_user テーブル（ユーザー認証用）
-- =============================================
CREATE TABLE IF NOT EXISTS app_user (
    user_account VARCHAR(50) PRIMARY KEY,
    password VARCHAR(255),
    display_name VARCHAR(100),
    role VARCHAR(50),
    person_id BIGINT,
    google_subject VARCHAR(255),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    UNIQUE (google_subject),
    CONSTRAINT fk_app_user_person FOREIGN KEY (person_id) REFERENCES person (person_id)
);
-- =============================================
-- =============================================
-- composer_mst テーブル（作曲家マスター）
-- =============================================
CREATE TABLE IF NOT EXISTS composer_mst (
    composer_id VARCHAR(5) NOT NULL,
    composer_name VARCHAR(64) NOT NULL,
    composer_name_jp VARCHAR(64) NOT NULL,
    birth_date_str VARCHAR(32),
    death_date_str VARCHAR(32),
    first_play VARCHAR(16),
    age_at_death INT,
    orthographic_variants VARCHAR(64),
    main_country VARCHAR(64),
    is_japanese BOOLEAN,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (composer_id)
);
-- =============================================
-- music_mst テーブル（曲マスター）
-- =============================================
CREATE TABLE IF NOT EXISTS music_mst (
    music_id VARCHAR(12) NOT NULL,
    composer_id VARCHAR(5) NOT NULL,
    composer_name VARCHAR(64) NOT NULL,
    arranger_id VARCHAR(5),
    arranger_name VARCHAR(64),
    music_title_formal_jp VARCHAR(128) NOT NULL,
    music_title_formal VARCHAR(128),
    music_title_lang VARCHAR(8),
    music_alias_title_jp VARCHAR(16),
    music_alias_title VARCHAR(64),
    music_alias_lang VARCHAR(8),
    play_time INT,
    orchestrate VARCHAR(128),
    music_type_id VARCHAR(2),
    music_no INT,
    music_other_no INT,
    opus_no INT,
    opus_no_eda INT,
    music_index_type VARCHAR(16),
    music_index_no INT,
    music_index_no_eda INT,
    music_key_id VARCHAR(16),
    compose_at VARCHAR(16),
    first_play VARCHAR(16),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (music_id)
);
-- =============================================
-- concert_program テーブル（演奏会プログラム）
-- =============================================
CREATE TABLE IF NOT EXISTS concert_program (
    concert_id VARCHAR(12) NOT NULL,
    program_no INT NOT NULL,
    music_id VARCHAR(12),
    music_title_formal_jp TEXT NOT NULL,
    from_part VARCHAR(64),
    memo TEXT,
    mov_service VARCHAR(64),
    mov_id VARCHAR(64),
    mov_owner VARCHAR(64),
    mov_url VARCHAR(256),
    mov_is_public BOOLEAN,
    layout_id BIGINT,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (concert_id, program_no),
    CONSTRAINT fk_concert_program_concert FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);
-- 既存テーブルが VARCHAR(128) で作成されていた場合に TEXT へ変換
ALTER TABLE concert_program
ALTER COLUMN music_title_formal_jp TYPE TEXT;
-- 既存テーブルへの舞台配置ID列の追加
ALTER TABLE concert_program
ADD COLUMN IF NOT EXISTS layout_id BIGINT;
-- =============================================
-- stage_layout テーブル（舞台配置マスタ）
--   concert_program.layout_id から参照される。
--   1つの配置を複数の曲で使い回せるよう、独立したマスタとして持つ。
-- =============================================
CREATE TABLE IF NOT EXISTS stage_layout (
    layout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_name VARCHAR(64) NOT NULL,
    orch_name VARCHAR(64),
    stage_width INT NOT NULL,
    stage_depth INT NOT NULL,
    memo TEXT,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system'
);
-- =============================================
-- stage_layout_seat テーブル（舞台配置の座席 = stage_layout の子テーブル）
--   座標系: 舞台を真上から見た図。原点は左上、x は下手→上手、y は舞台奥→客席側。
--           つまり y が大きいほど客席に近い（指揮者は手前＝y の大きい側）。
--   rotation: 正面の向き。0 = 画面上（舞台奥）向き、時計回りに 0-359 度。
--             客席を向く場合は 180。既定では全員が指揮者を向く角度を入れる。
-- =============================================
CREATE TABLE IF NOT EXISTS stage_layout_seat (
    seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_id BIGINT NOT NULL,
    seat_no INT NOT NULL,
    role_type VARCHAR(16) NOT NULL,
    part_code VARCHAR(16),
    part_name VARCHAR(32),
    pult_no INT,
    seat_side VARCHAR(8),
    person_id BIGINT,
    person_name VARCHAR(32),
    pos_x INT NOT NULL,
    pos_y INT NOT NULL,
    rotation INT NOT NULL,
    memo VARCHAR(128),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system'
);
-- =============================================
-- orch_member テーブル（団体所属メンバー）
--   レイアウトに割り当てられた人物を、使用団体単位で自動登録する。
-- =============================================
CREATE TABLE IF NOT EXISTS orch_member (
    person_id BIGINT NOT NULL,
    orch_id VARCHAR(6) NOT NULL,
    start_date DATE NOT NULL DEFAULT DATE '1900-01-01',
    end_date DATE,
    main_active_instrument VARCHAR(32),
    is_member BOOLEAN DEFAULT TRUE,
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (person_id, orch_id),
    CONSTRAINT fk_orch_member_person FOREIGN KEY (person_id) REFERENCES person (person_id),
    CONSTRAINT fk_orch_member_orch FOREIGN KEY (orch_id) REFERENCES orch_mst (orch_id)
);
CREATE INDEX IF NOT EXISTS idx_orch_member_orch ON orch_member (orch_id);
-- =============================================
-- concert_member テーブル（演奏会出演メンバー）
--   oconcert_id は concert.concert_id を参照する演奏会ID。
-- =============================================
CREATE TABLE IF NOT EXISTS concert_member (
    person_id BIGINT NOT NULL,
    oconcert_id VARCHAR(12) NOT NULL,
    main_active_instrument VARCHAR(32),
    is_member BOOLEAN DEFAULT TRUE,
    is_part_leader BOOLEAN DEFAULT FALSE,
    is_concert_master BOOLEAN DEFAULT FALSE,
    coordinator VARCHAR(64),
    create_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_datetime TIMESTAMP,
    delete_datetime TIMESTAMP,
    update_by VARCHAR(64) DEFAULT 'system',
    PRIMARY KEY (person_id, oconcert_id),
    CONSTRAINT fk_concert_member_person FOREIGN KEY (person_id) REFERENCES person (person_id),
    CONSTRAINT fk_concert_member_concert FOREIGN KEY (oconcert_id) REFERENCES concert (concert_id)
);
CREATE INDEX IF NOT EXISTS idx_concert_member_concert ON concert_member (oconcert_id);
CREATE INDEX IF NOT EXISTS idx_stage_layout_seat_layout ON stage_layout_seat (layout_id);
-- =============================================
-- 監査項目の追加（既存テーブル / PostgreSQL 既存DB向け。何度実行しても安全）
--   delete_datetime が NULL のレコードのみ有効データとして扱う。
-- =============================================
ALTER TABLE rehea_analysis_correction_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_instrument_keyword_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_include_keyword_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_measure_pattern_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_measure_pattern_mst
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_measure_pattern_mst
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE rehea_analysis_mark_pattern_mst
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_mark_pattern_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_mark_pattern_mst
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE rehea_analysis_mark_pattern_mst
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE orch_mst
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE orch_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE orch_mst
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE orch_mst
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE concert
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE concert
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE concert
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE concert
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE person
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE person
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE person
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE person
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE category
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE category
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE category
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE category
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE concert_lesson
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE concert_lesson
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE concert_lesson
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE concert_lesson
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE app_user
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE composer_mst
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE composer_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE composer_mst
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE composer_mst
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE music_mst
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE music_mst
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE music_mst
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE music_mst
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE concert_program
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE concert_program
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE concert_program
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE concert_program
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE stage_layout
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE stage_layout
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;
ALTER TABLE stage_layout
ADD COLUMN IF NOT EXISTS delete_datetime TIMESTAMP;
ALTER TABLE stage_layout
ADD COLUMN IF NOT EXISTS update_by VARCHAR(64);
ALTER TABLE stage_layout_seat
ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP;
ALTER TABLE stage_layout_seat
ADD COLUMN IF NOT EXISTS update_datetime TIMESTAMP;