-- =============================================
-- schema.sql - テーブル定義（H2 / PostgreSQL 互換）
-- =============================================

CREATE TABLE IF NOT EXISTS correction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INT NOT NULL,
    wrong_text VARCHAR(255) NOT NULL,
    correct_text VARCHAR(255) NOT NULL,
    UNIQUE (wrong_text)
);

CREATE TABLE IF NOT EXISTS instrument_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name VARCHAR(255) NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    UNIQUE (canonical_name, keyword)
);

CREATE TABLE IF NOT EXISTS include_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    UNIQUE (keyword)
);

CREATE TABLE IF NOT EXISTS exclude_pattern (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    UNIQUE (pattern)
);

CREATE TABLE IF NOT EXISTS measure_pattern (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    UNIQUE (pattern)
);

CREATE TABLE IF NOT EXISTS rehearsal_mark_pattern (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    UNIQUE (pattern)
);
