-- =============================================
-- schema.sql - テーブル定義（H2 / PostgreSQL 互換）
-- =============================================

CREATE TABLE IF NOT EXISTS correction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INT NOT NULL,
    wrong_text VARCHAR(255) NOT NULL,
    correct_text VARCHAR(255) NOT NULL,
    UNIQUE (wrong_text)
);

CREATE TABLE IF NOT EXISTS instrument_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name VARCHAR(255) NOT NULL,
    keyword VARCHAR(255) NOT NULL,
    UNIQUE (canonical_name, keyword)
);

CREATE TABLE IF NOT EXISTS include_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    UNIQUE (keyword)
);

CREATE TABLE IF NOT EXISTS exclude_pattern (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    UNIQUE (pattern)
);

CREATE TABLE IF NOT EXISTS measure_pattern (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    UNIQUE (pattern)
);

CREATE TABLE IF NOT EXISTS rehearsal_mark_pattern (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern VARCHAR(255) NOT NULL,
    UNIQUE (pattern)
);

-- =============================================
-- orch_data テーブル（オーケストラ団体マスタ）
-- =============================================

CREATE TABLE IF NOT EXISTS orch_data (
    orch_id      VARCHAR(6)   NOT NULL,
    orch_name    VARCHAR(64)  NOT NULL,
    orch_name_en VARCHAR(64),
    orch_type    VARCHAR(10),
    homepage_url VARCHAR(256),
    description  TEXT,
    activity     BOOLEAN,
    pro_state    INT,
    is_public    BOOLEAN,
    creator      INT,
    since        INT,
    PRIMARY KEY (orch_id),
    UNIQUE (orch_name)
);

-- =============================================
-- concert_data テーブル（演奏会データ）
-- =============================================

CREATE TABLE IF NOT EXISTS concert_data (
    concert_id        VARCHAR(12)  NOT NULL,
    orch_id           VARCHAR(6)   NOT NULL,
    concert_main_id   VARCHAR(12)  NOT NULL,
    concert_sub_id    VARCHAR(2)   NOT NULL,
    concert_name      VARCHAR(128),
    music_descript    TEXT,
    conductor_id      BIGINT,
    conductor_name    VARCHAR(20),
    concert_num       BIGINT,
    hall_id           VARCHAR(6),
    hall_branch_id    BIGINT,
    place_name        VARCHAR(64),
    concert_date      VARCHAR(12),
    open_time         VARCHAR(6),
    open_space        VARCHAR(6),
    price             BIGINT,
    price_under_cond  VARCHAR(16),
    price_under       BIGINT,
    teket_url         VARCHAR(128),
    PRIMARY KEY (concert_id)
);

-- =============================================
-- person テーブル（人物マスタ）
-- =============================================

CREATE TABLE IF NOT EXISTS person (
    person_id                  BIGINT        NOT NULL,
    last_name                  VARCHAR(8)    NOT NULL,
    first_name                 VARCHAR(8)    NOT NULL,
    old_name                   VARCHAR(8),
    last_name_kana             VARCHAR(12),
    first_name_kana            VARCHAR(12),
    last_name_kana_estimate    VARCHAR(12)   NOT NULL,
    first_name_kana_estimate   VARCHAR(12)   NOT NULL,
    musician_status            VARCHAR(12),
    main_active_instrument     VARCHAR(32),
    main_active_orch           VARCHAR(32),
    orch_since                 INT,
    account                    VARCHAR(32),
    PRIMARY KEY (person_id)
);

-- =============================================
-- lesson_data テーブル（練習データ）
-- =============================================

CREATE TABLE IF NOT EXISTS lesson_data (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_main_id       VARCHAR(12)  NOT NULL,
    branch_no             INT          NOT NULL,
    lesson_date           DATE         NOT NULL,
    lesson_start_time_str VARCHAR(32),
    lesson_end_time_str   VARCHAR(32),
    lesson_start_time     TIMESTAMP,
    lesson_end_time       TIMESTAMP,
    place_name            VARCHAR(64),
    contain               VARCHAR(256)
);

-- =============================================
-- app_user テーブル（ユーザー認証用）
-- =============================================

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(100),
    role VARCHAR(50),
    UNIQUE (username)
);
